# Generated by Django 3.2.5 on 2021-08-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orignal_image_url', models.URLField(max_length=256)),
                ('rekognized_image_url', models.URLField(max_length=256)),
                ('gender', models.CharField(max_length=16)),
                ('age_low', models.IntegerField(blank=True, null=True)),
                ('age_high', models.IntegerField(blank=True, null=True)),
                ('emotion', models.CharField(max_length=64)),
                ('image_fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.image')),
            ],
        ),
    ]
