# Generated by Django 3.2.5 on 2021-08-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0002_boundingbox_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='beard',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='eyeglasses',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='eyes_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='mouth_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='mustache',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='smile',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='sunglasses',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
