# Generated by Django 3.2.5 on 2021-08-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('rekognition_type', models.CharField(choices=[('FACE', 'Face Rekognition'), ('OBJECT', 'Object Rekognition'), ('TEXT', 'Text Rekognition')], default=None, max_length=6)),
            ],
        ),
    ]
